# Site settings
title: Anjuan Simmons
email: Please use the Contact Me page
description: > # this means to ignore newlines until "baseurl:"
  I'm a Technology Translator. Welcome to my site.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anjuan.github.io/" # the base hostname & protocol for your site
twitter_username: anjuan
github_username:  anjuan

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
jobtitle: "Technology Translator"
excerpt_separator: "<!--more-->"

# SEO stuff
google_author: "https://plus.google.com/u/0/+AnjuanSimmons"

gems:
  - jekyll-sitemap
